version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: github.com/hyperyuri/webapi-db
    container_name: books-api-go
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
    volumes:
      - books-api-go:/var/lib/postgresql/data

volumes:
  books-api-go:
